create database customer_beheviour;
use customer_beheviour ;

select * from customer limit 10;

-- Q.1. What is total revenue generated by male vs. female customers ?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q.2 Which customers used a discount but still spentt more than the average purchase amount?
select customer_id , purchase_amount
from customer
where  discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

-- Q.3- Which are top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as "Average review rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5 ;

-- Q.4- Compare the average purchase amount between standard and express shipping
select shipping_type,round( avg(purchase_amount),2)
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

-- Q.5- Do subscribed customers spend more ? compare avg spend and total revenue
-- 	between subscribers and non subscribers.
select subscription_status,
count(customer_id) as total_customers , 
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_reveue
from customer
group by subscription_status
order by total_reveue,avg_spend desc;

-- Q.6- Which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased,
round(100 *  sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

-- Q.7  Segment customers into new,returning , and loyal based on their total
--      number of previus purchases , and show the count of each segment.
select * from customer;

WITH customer_type AS (
    SELECT  customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)
SELECT  customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

--   Q.8  What are the top 3 most purchased products within each category
WITH item_count AS (
    SELECT category, item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank , category , item_purchased , total_orders
FROM item_count
WHERE item_rank <= 3;

-- Q.9- Are customers who are  repeat buyers (more than 5 previous purchase) also likely o subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q.10- What is revenue contribution of each age group?
select age_group,
sum(purchase_amount) as  total_revenue
from customer
group by age_group
order by total_revenue desc  ;
